apiVersion: apps/v1
kind: Deployment
metadata:
  name: podinfo  
spec:
  selector:
    matchLabels:
      app: podinfo  
  template:
    metadata:
      labels:
        app: podinfo
    spec:
      containers:
        - name: podinfo
          env:
            - name: PODINFO_UI_COLOR
              value: "#007300" 

