apiVersion: apps/v1
kind: Deployment
metadata:
  name: providers.notification.toolkit.fluxcd.io  
spec:
  selector:
    matchLabels:
      app: podinfo  
  template:
    metadata:
      labels:
        app: podinfo
    spec:
      containers:
      - name: podinfo
        image: ghcr.io/stefanprodan/podinfo:5.0.0
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - nama: http
          containerPort: 9898
          protocol: TCP
